### ISSUE TITLE
Panic while type some non-exist message

### ISSUE THREAD

**Issue by Gaojianli** [lasorda/protobuf-language-server#6]
```
panic: runtime error: index out of range [-1]

goroutine 23 [running]:
pls/components.getWord({0x0?, 0xc0001522a0?}, 0x63?, 0x0?)
	/Users/gaojianli/protobuf-language-server/components/jump_definition.go:250 +0x112
pls/components.Completion({0x0?, 0x0?}, 0xc000151ac0)
	/Users/gaojianli/protobuf-language-server/components/completion.go:16 +0xc5
github.com/TobiasYin/go-lsp/lsp.(*Methods).completion(0x0?, {0x1232a58?, 0xc0001d2f00?}, {0x119a120?, 0xc000151ac0?})
	/Users/gaojianli/protobuf-language-server/go-lsp/lsp/methods_gen.go:428 +0x53
github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute.func1()
	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:208 +0xbc
created by github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute
	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:206 +0x29f
```

**Comment by Gaojianli** [comment]
another panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1162ad3]

goroutine 41 [running]:
pls/proto/view.(*view).setContent(0xc0000a3d70, {0xc000281900?, 0x498?}, {0xc0002bc5b0, 0x6b}, {0xc0001b7400, 0x498, 0x500})
	/Users/gaojianli/protobuf-language-server/proto/view/view.go:73 +0x213
pls/proto/view.didChange({0x1232a58, 0xc000394570}, 0xc0002ed110)
	/Users/gaojianli/protobuf-language-server/proto/view/view.go:274 +0xdb
github.com/TobiasYin/go-lsp/lsp.(*Methods).didChangeTextDocument(0x0?, {0x1232a58?, 0xc000394570?}, {0x119a420?, 0xc0002ed110?})
	/Users/gaojianli/protobuf-language-server/go-lsp/lsp/methods_gen.go:260 +0x53
github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute.func1()
	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:208 +0xbc
created by github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute
	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:206 +0x29f
```

**Comment by lasorda** [comment]
> ```
> panic: runtime error: index out of range [-1]
> 
> goroutine 23 [running]:
> pls/components.getWord({0x0?, 0xc0001522a0?}, 0x63?, 0x0?)
> 	/Users/gaojianli/protobuf-language-server/components/jump_definition.go:250 +0x112
> pls/components.Completion({0x0?, 0x0?}, 0xc000151ac0)
> 	/Users/gaojianli/protobuf-language-server/components/completion.go:16 +0xc5
> github.com/TobiasYin/go-lsp/lsp.(*Methods).completion(0x0?, {0x1232a58?, 0xc0001d2f00?}, {0x119a120?, 0xc000151ac0?})
> 	/Users/gaojianli/protobuf-language-server/go-lsp/lsp/methods_gen.go:428 +0x53
> github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute.func1()
> 	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:208 +0xbc
> created by github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute
> 	/Users/gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:206 +0x29f
> ```

https://github.com/lasorda/protobuf-language-server/commit/f986125225e1ea9d052494bff718703e2e4cedb6 this may solve
