### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by Gaojianli** [lasorda/protobuf-language-server#8]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1162ad3]

goroutine 13 [running]:
pls/proto/view.(*view).setContent(0xc00010fd70, {0xc00022a880?, 0xc9c?}, {0xc000100460, 0x63}, {0xc00030db00, 0xc9c, 0xd80})
	/Users/Gaojianli/protobuf-language-server/proto/view/view.go:73 +0x213
pls/proto/view.didChange({0x1232a78, 0xc00023d8c0}, 0xc00023c4b0)
	/Users/Gaojianli/protobuf-language-server/proto/view/view.go:274 +0xdb
github.com/TobiasYin/go-lsp/lsp.(*Methods).didChangeTextDocument(0x0?, {0x1232a78?, 0xc00023d8c0?}, {0x119a440?, 0xc00023c4b0?})
	/Users/Gaojianli/protobuf-language-server/go-lsp/lsp/methods_gen.go:260 +0x53
github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute.func1()
	/Users/Gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:208 +0xbc
created by github.com/TobiasYin/go-lsp/jsonrpc.(*Session).execute
	/Users/Gaojianli/protobuf-language-server/go-lsp/jsonrpc/session.go:206 +0x29f
[Error - 2:52:00 PM] The protobuf-language-server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by lasorda** [comment]
给个proto文件看看
